version: '3.8'

services:
  pdf-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3005:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev

networks:
  default:
    name: pdf-service-network
